version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=muscu
      - JWT_SECRET=yourjwtsecret
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: muscu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
